# Generated by Django 3.2.25 on 2024-03-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='mention',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
