# Generated by Django 3.2.25 on 2024-03-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectdetails_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='codeLink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='deployedLink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='designLink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
