# Generated by Django 3.2.25 on 2024-03-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20240314_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlinks',
            name='link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='projectlinks',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectlinks',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
